on:
  push:
    branches:
      - master  # or master (check your branch)
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Tag to run (smoke/regression)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - run: playwright install --with-deps

      - name: Run tests
        run: |
          if [ -z "${{ github.event.inputs.test_tag }}" ]; then
            pytest -s -v
          else
            pytest -s -v -m "${{ github.event.inputs.test_tag }}"
          fi